In [11]:
import time
import numpy as np
import pandas as pd
import os
import re
import datetime
import glob

# from dotenv import load_dotenv
from bs4 import BeautifulSoup
import urllib.request as req
import requests

In [3]:
os.getcwd()

'C:\\Users\\fuku_k\\Documents\\pypro\\vleague_stats'

In [6]:
path = 'database/v1_m/teamdb_2021-22_regular.csv'
df = pd.read_csv(path)
df

,AA,AP,AE,ASucc%,AP/S,BAA,BAP,BAE,BASucc%,BP,...,OpBP/S,OpSVA,OpSVP,OpSVE,OpSVx,OpSVEff%,OpRA,OpRx,OpRg,OpRSucc%
0,124,49,9,39.5,12.25,30,16,2,53.3,2,...,5.00,94,1,11,19,3.2,63,26.0,18.0,55.6
1,98,43,11,43.9,10.75,18,9,2,50.0,20,...,0.50,82,4,19,15,3.7,82,35.0,28.0,59.8
2,109,49,10,45.0,12.25,28,14,3,50.0,10,...,3.00,92,5,12,32,10.9,68,33.0,16.0,60.3
3,98,51,5,52.0,12.75,27,15,1,55.6,12,...,2.50,83,1,14,19,2.7,78,30.0,14.0,47.4
4,87,40,8,46.0,10.00,20,9,4,45.0,16,...,1.25,98,9,24,20,8.2,76,26.0,20.0,47.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
333,115,52,7,45.2,13.00,26,10,1,38.5,2,...,2.75,96,2,20,15,0.8,73,29.0,18.0,52.1
334,109,52,8,47.7,13.00,19,10,1,52.6,7,...,2.25,94,10,13,25,13.8,72,30.0,23.0,57.6
335,108,55,9,50.9,13.75,32,15,3,46.9,9,...,1.75,88,6,12,17,8.2,77,28.0,19.0,48.7
336,98,55,7,56.1,13.75,24,15,3,62.5,8,...,2.75,99,4,18,18,4.0,80,26.0,31.0,51.9
337,113,63,7,55.8,15.75,15,11,1,73.3,11,...,2.00,93,1,12,23,4.0,80,34.0,25.0,58.1

In [12]:
division = 'v1_m'
tree = glob.glob('database/{}/*'.format(division))
print(tree)

['database/v1_m\\playerdb_2019-20_regular.csv', 'database/v1_m\\playerdb_2021-22_regular.csv', 'database/v1_m\\teamdb_2019-20_regular.csv', 'database/v1_m\\teamdb_2021-22_regular.csv']

In [77]:
# df.iloc[:, 30:]
f = lambda x: 1 if x == 'Win' else 0
df['Win'] = df['Win Lose'].map(f)
df['Win']

0      0
1      1
2      0
3      1
4      0
      ..
333    0
334    0
335    1
336    0
337    1
Name: Win, Length: 338, dtype: int64

In [78]:
df.columns

Index(['AA', 'AP', 'AE', 'ASucc%', 'AP/S', 'BAA', 'BAP', 'BAE', 'BASucc%',
       'BP', 'BP/S', 'SVA', 'SVP', 'SVE', 'SVx', 'SVEff%', 'RA', 'Rx', 'Rg',
       'RSucc%', 'MatchNo.', 'Date', 'Year', 'Month', 'Day', 'Place', 'Venue',
       'Team', 'Op.Team', 'Director', 'Coach', 'Win Set', 'Lose Set',
       'Total Set', 'Win Lose', 'Get Point', 'Lose Point', 'Game Time',
       'Start Time', 'End Time', 'Spectators', 'Jury', 'Chief Umpire',
       'Sub Umpire', 'Judgeman', 'Home Away', 'OpAA', 'OpAP', 'OpAE',
       'OpASucc%', 'OpAP/S', 'OpBAA', 'OpBAP', 'OpBAE', 'OpBASucc%', 'OpBP',
       'OpBP/S', 'OpSVA', 'OpSVP', 'OpSVE', 'OpSVx', 'OpSVEff%', 'OpRA',
       'OpRx', 'OpRg', 'OpRSucc%', 'Win'],
      dtype='object')

In [79]:
df2 = df[['AA', 'AP', 'AE', 'ASucc%', 'AP/S', 'BAA', 'BAP', 'BAE', 'BASucc%',
       'BP', 'BP/S', 'SVA', 'SVP', 'SVE', 'SVx', 'SVEff%', 'RA', 'Rx', 'Rg',
       'RSucc%']]
df2['BASucc%'] = df2['BASucc%'].replace('-', 0).astype(float)

C:\Users\fuku_k\AppData\Local\Temp/ipykernel_7656/3469499047.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['BASucc%'] = df2['BASucc%'].replace('-', 0).astype(float)

In [80]:
df3 = df2.apply(lambda x: (x-x.mean())/x.std(), axis=0)
df3

,AA,AP,AE,ASucc%,AP/S,BAA,BAP,BAE,BASucc%,BP,BP/S,SVA,SVP,SVE,SVx,SVEff%,RA,Rx,Rg,RSucc%
0,1.041229,0.003832,0.850448,-1.392039,-0.447047,1.079422,1.031703,-0.079833,0.176094,-1.556899,-1.593278,-0.101920,0.028557,1.023024,-0.639309,-0.690938,0.899946,0.572100,1.812021,0.435637
1,-0.103133,-0.514269,1.568180,-0.757929,-1.263520,-0.528414,-0.476023,-0.079833,-0.078958,3.340812,2.970347,0.579116,-1.230453,-0.678241,-0.104110,-0.829405,-0.318320,-0.402874,0.255175,-0.047814
2,0.381020,0.003832,1.209314,-0.599402,-0.447047,0.811450,0.600924,0.578306,-0.078958,0.619861,0.435000,-0.045167,-1.230453,-0.040267,-0.104110,-0.967871,0.643469,0.030448,-0.367563,-0.991694
3,-0.103133,0.176533,-0.585015,0.409408,-0.174889,0.677463,0.816313,-0.737973,0.353858,1.164051,0.942069,0.465610,0.448228,-0.465583,1.635285,1.302976,0.002276,0.355439,-0.056194,0.493191
4,-0.587286,-0.773320,0.491582,-0.455286,-1.671756,-0.260441,-0.476023,1.236445,-0.465400,2.252432,1.956208,0.408857,-0.391113,-0.040267,1.233886,0.333712,0.066396,0.680431,-1.145986,0.309019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
333,0.645103,0.262883,0.132717,-0.570579,-0.038811,0.543477,-0.260634,-0.737973,-0.967775,-1.556899,-1.593278,0.125092,0.028557,-0.252925,0.297288,0.306019,0.451111,0.138778,1.812021,0.458658
334,0.381020,0.262883,0.491582,-0.210290,-0.038811,-0.394427,-0.260634,-0.737973,0.121992,-0.196424,-0.325605,0.238598,0.867898,-0.465583,-0.371710,0.555258,0.579350,-0.186213,0.410860,-0.842054
335,0.337006,0.521933,0.850448,0.250881,0.369426,1.347395,0.816313,0.578306,-0.318552,0.347766,0.181465,0.579116,2.546578,-0.252925,0.698687,2.106080,0.258754,0.030448,1.033598,0.182401
336,-0.103133,0.521933,0.132717,1.000283,0.369426,0.275504,0.816313,0.578306,0.887148,0.075671,-0.072070,0.522363,-1.230453,-0.465583,0.431088,-0.607859,0.771708,0.463770,1.344967,0.239955
337,0.557076,1.212735,0.132717,0.957048,1.458056,-0.930372,-0.045245,-0.737973,1.721864,0.891956,0.688534,0.862881,0.028557,0.810366,-0.237910,-0.607859,0.771708,-0.402874,2.279075,-0.473711

In [81]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 338 entries, 0 to 337
Data columns (total 20 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   AA       338 non-null    float64
 1   AP       338 non-null    float64
 2   AE       338 non-null    float64
 3   ASucc%   338 non-null    float64
 4   AP/S     338 non-null    float64
 5   BAA      338 non-null    float64
 6   BAP      338 non-null    float64
 7   BAE      338 non-null    float64
 8   BASucc%  338 non-null    float64
 9   BP       338 non-null    float64
 10  BP/S     338 non-null    float64
 11  SVA      338 non-null    float64
 12  SVP      338 non-null    float64
 13  SVE      338 non-null    float64
 14  SVx      338 non-null    float64
 15  SVEff%   338 non-null    float64
 16  RA       338 non-null    float64
 17  Rx       338 non-null    float64
 18  Rg       338 non-null    float64
 19  RSucc%   338 non-null    float64
dtypes: float64(20)
memory usage: 52.9 KB

In [82]:
import seaborn as sns
import matplotlib.pyplot as plt
# sns.pairplot(df2)
# plt.show()

In [83]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

X = df3 # 説明変数
Y = df['Win']
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0) # 80%のデータを学習データに、20%を検証データにする

lr = LogisticRegression() # ロジスティック回帰モデルのインスタンスを作成
lr_ = lr.fit(X_train, Y_train) # ロジスティック回帰モデルの重みを学習

In [84]:
lr.coef_[0]

array([ 1.16362042,  1.02664264, -0.35031714,  0.44645793,  0.29028917,
        0.09154701, -0.13214367, -0.11307234,  0.23142305,  0.24252404,
        1.02479222,  0.30112813,  0.43700846,  0.45018679,  0.36501021,
        0.74765198, -2.19512833, -0.80952625, -0.22325729,  1.16913543])

In [85]:
df3.columns

Index(['AA', 'AP', 'AE', 'ASucc%', 'AP/S', 'BAA', 'BAP', 'BAE', 'BASucc%',
       'BP', 'BP/S', 'SVA', 'SVP', 'SVE', 'SVx', 'SVEff%', 'RA', 'Rx', 'Rg',
       'RSucc%'],
      dtype='object')

In [86]:
lr_.summary()

AttributeError: 'LogisticRegression' object has no attribute 'summary'

In [90]:
Y_pred = lr.predict(X_test)
print(Y_pred)
print(Y_test)
count = 0
for i,j in zip(Y_pred, Y_test):
    if i == j:
        count += 1
print(count/len(Y_pred))

[1 1 0 0 0 1 0 0 1 1 0 0 1 0 0 1 0 0 1 0 0 1 1 0 1 1 1 0 1 0 0 0 0 0 1 1 0
 0 1 0 0 1 0 0 1 1 0 0 0 1 1 1 1 0 1 1 1 1 0 1 0 1 0 1 0 1 1 0]
76     1
269    1
327    0
158    0
200    1
      ..
134    1
65     0
103    1
66     1
275    0
Name: Win, Length: 68, dtype: int64
0.9411764705882353

In [87]:
df4 = pd.DataFrame(list(zip(df3.columns, lr.coef_[0])), columns=['stats', 'coef_'])
df4

      stats     coef_
0        AA  1.163620
1        AP  1.026643
2        AE -0.350317
3    ASucc%  0.446458
4      AP/S  0.290289
5       BAA  0.091547
6       BAP -0.132144
7       BAE -0.113072
8   BASucc%  0.231423
9        BP  0.242524
10     BP/S  1.024792
11      SVA  0.301128
12      SVP  0.437008
13      SVE  0.450187
14      SVx  0.365010
15   SVEff%  0.747652
16       RA -2.195128
17       Rx -0.809526
18       Rg -0.223257
19   RSucc%  1.169135

In [ ]:
df4 = pd.DataFrame(list(zip(df3.columns, lr.coef_[0])), columns=['stats', 'coef_'])
df4